## Python Numpy 

===============================

Author: Abhishek Dey

===============================

### Import numpy library

In [2]:
import numpy as np

### Converting a list to numpy array

In [3]:
l=[1,2,3,4,5,6]

In [5]:
a=np.array(l)

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
type(a)

numpy.ndarray

### Creating a one dimensional array

In [8]:
a1=np.array([[1,2,3]])

In [9]:
a1

array([[1, 2, 3]])

### Creating a two dimensional array

In [10]:
a2=np.array([[1,2,3],[4,5,6]])

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

### Creating multi-dimensional arrays

In [12]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [16]:
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Indexing in numpy array

In [51]:
a4[0]

array([1, 2, 3])

In [52]:
a4[1]

array([4, 5, 6])

In [53]:
a4[2]

array([7, 8, 9])

### Slicing in numpy array

In [55]:
a4[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a4[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a4[0:4:2]

array([[1, 2, 3],
       [7, 8, 9]])

## Matrix Operations using numpy

In [27]:
A = np.array([[1,2],[4,5]])

In [28]:
A

array([[1, 2],
       [4, 5]])

### Trace of a matrix (Sum of diagonal elements)

In [29]:
A_Trace = np.trace(A)

In [30]:
A_Trace

6

### Transpose of a matrix 

In [31]:
A_Trans = np.transpose(A)

In [32]:
A_Trans

array([[1, 4],
       [2, 5]])

### Rank of a matrix

In [33]:
A_Rank = np.linalg.matrix_rank(A)

In [34]:
A_Rank

2

### Matrix addition

In [35]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
B

array([[5, 6],
       [7, 8]])

In [38]:
Sum_AB = np.add(A,B)

In [39]:
Sum_AB

array([[ 6,  8],
       [10, 12]])

### Matrix substraction

In [40]:
Subs_AB = np.subtract(A,B)

In [41]:
Subs_AB

array([[-4, -4],
       [-4, -4]])

### Matrix multiplication

In [42]:
Mul_AB = np.matmul(A,B)

In [43]:
Mul_AB

array([[19, 22],
       [43, 50]])